[book]
title = "Bintan's Wiki"
authors = ["lubingtan"]
language = "en"

[preprocessor.blog]
command = "tools/blog-preprocessor.py"
[build]
create-missing = true
[output.html]
no-section-label = true
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
definition-lists = true
admonitions = true
mathjax-support = false
git-repository-url = "https://github.com/lubingtan/lubingtan.github.io"
edit-url-template = "https://github.com/lubingtan/lubingtan.github.io/edit/main/{path}"
git-repository-icon = "fab-github"
[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0