[book]
title = "Bintan's Wiki"
authors = ["lubingtan"]
language = "en"
src = "."

[preprocessor.blog]
command = "tools/blog-preprocessor.py"
[build]
create-missing = true
[output.html]
no-section-label = true
[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0